repos:
  - repo: local
    hooks:
      - id: dart-format
        name: Dart Format
        entry: dart format --set-exit-if-changed .
        language: system
        files: \.dart$

      - id: dart-fix
        name: Dart Fix
        entry: dart fix --apply .
        language: system
        pass_filenames: false
